#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App3.Resource", IsApplication=true)]

namespace App3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int myanimation = 2131034112;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int words = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int black = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int blue = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int red = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int white = 2131165186;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_horizontal_margin = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int activity_vertical_margin = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arm1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arm2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int body = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int download = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gallows = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int head = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int humanlefthandup = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int leg1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int leg2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int letter_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int letter_down = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int letter_up = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int man = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int title = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b001b
			public const int action_menu = 2131427355;
			
			// aapt resource value: 0x7f0b0010
			public const int alphabets = 2131427344;
			
			// aapt resource value: 0x7f0b0001
			public const int btn = 2131427329;
			
			// aapt resource value: 0x7f0b0013
			public const int btnhome = 2131427347;
			
			// aapt resource value: 0x7f0b001a
			public const int btnret = 2131427354;
			
			// aapt resource value: 0x7f0b0000
			public const int edt = 2131427328;
			
			// aapt resource value: 0x7f0b0005
			public const int manarm1 = 2131427333;
			
			// aapt resource value: 0x7f0b000b
			public const int manarm11 = 2131427339;
			
			// aapt resource value: 0x7f0b0006
			public const int manarm2 = 2131427334;
			
			// aapt resource value: 0x7f0b000c
			public const int manarm21 = 2131427340;
			
			// aapt resource value: 0x7f0b0004
			public const int manbody = 2131427332;
			
			// aapt resource value: 0x7f0b000a
			public const int manbody1 = 2131427338;
			
			// aapt resource value: 0x7f0b0003
			public const int manhead = 2131427331;
			
			// aapt resource value: 0x7f0b0009
			public const int manhead1 = 2131427337;
			
			// aapt resource value: 0x7f0b0007
			public const int manleg1 = 2131427335;
			
			// aapt resource value: 0x7f0b000d
			public const int manleg11 = 2131427341;
			
			// aapt resource value: 0x7f0b0008
			public const int manleg2 = 2131427336;
			
			// aapt resource value: 0x7f0b000e
			public const int manleg21 = 2131427342;
			
			// aapt resource value: 0x7f0b0014
			public const int rl = 2131427348;
			
			// aapt resource value: 0x7f0b0002
			public const int txt = 2131427330;
			
			// aapt resource value: 0x7f0b0017
			public const int txtanimals = 2131427351;
			
			// aapt resource value: 0x7f0b0016
			public const int txtbird = 2131427350;
			
			// aapt resource value: 0x7f0b0015
			public const int txtcity = 2131427349;
			
			// aapt resource value: 0x7f0b0018
			public const int txtflower = 2131427352;
			
			// aapt resource value: 0x7f0b0012
			public const int txtname = 2131427346;
			
			// aapt resource value: 0x7f0b0011
			public const int txtpoints = 2131427345;
			
			// aapt resource value: 0x7f0b0019
			public const int txtscore = 2131427353;
			
			// aapt resource value: 0x7f0b000f
			public const int words = 2131427343;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int dialog = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int firstpage = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int gamenew = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int letter = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int result = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int secondpage = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int totalscores = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int menu1 = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int action_settings = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int app_name = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int arm = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int body = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int gallows = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int head = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int leg = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int menuItem1 = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int play = 2131296258;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
